### ISSUE TITLE
Optional body validation

### ISSUE THREAD

**Issue by l4u-co** [appsquickly/TyphoonRestClient#23]
Hi,

I have an API where a given route can either returns a 200 OK response with a body, or 204 No Content (with obviously no body).

I'm trying to handle it with a validation scheme for the case of a present body, but I'm failing to do this without getting an error when getting the 204 response (at that time only using standard json validation code).

Is there a simple way to handle this?

Thx

**Comment by alexgarbarev** [comment]
Let me check, this probably should be done inside the library, as it is standard http code.

**Comment by alexgarbarev** [comment]
Hey @laurent-dazzl , check the latest 1.8.0 version

BTW, it might be boring to create a lot of verbose requests and mapping files. So there is a tool called `gena` that can generate requests and mappers for you.

Just run `gena request CreateUser`, for example. 
In order to install gena, just run `gem install gena`. Note that some templates dependent on [TRCAPIClient](https://github.com/alexgarbarev/TRCAPIClient)- there are some helper files.

**Comment by l4u-co** [comment]
You fixed it, thanks!

I'll check Gena ASAP, for now I covered all my API needs.

Br.
